services:
  website-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-website:latest
    container_name: personal-homepage-website-prod
    restart: always
    depends_on:
      - backend-prod
    env_file:
      - ./apps/website/.env.prod
    ports:
      - "3250:4200"
    environment:
      - NODE_ENV=production
    expose:
      - 3250

  admin-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-admin:latest
    container_name: personal-homepage-admin-prod
    restart: always
    depends_on:
      - backend-prod
    env_file:
      - ./apps/admin/.env.prod
    ports:
      - "3650:80"
    environment:
      - NODE_ENV=production
    expose:
      - 3650

  backend-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend:latest
    container_name: personal-homepage-backend-prod
    restart: always
    depends_on:
      - migrator-prod
    env_file:
      - ./apps/backend/.env.prod
    ports:
      - 4650:5000
    expose:
      - 6600

  migrator-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend-migrator:latest
    container_name: personal-homepage-backend-migrator-prod
    env_file:
      - ./apps/backend/.env.prod
