version: "3.8"

networks:
  swarm:
    driver: overlay
    attachable: true

services:
  website-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-website:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
      - API_PREFIX=/api/v1
      - NEXT_PUBLIC_API_PREFIX=/api/v1
    ports:
      - target: 4200
        published: 3250
        protocol: tcp
        mode: host
    networks:
      - swarm

  admin-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-admin:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://ph_backend-prod:5000
    ports:
      - target: 80
        published: 3650
        protocol: tcp
        mode: host
    networks:
      - swarm

  backend-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      - ENV=development
      - BACKEND_PORT=5000
      - PUBLIC_URL=http://localhost:4650
      - FRONTEND_URL=http://ph_website-prod:4200
      - ADMIN_URL=http://ph_admin-prod:80
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_SECRET=${JWT_SECRET}
      - API_URL=${API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - target: 5000
        published: 4650
        protocol: tcp
        mode: host
    networks:
      - swarm

  migrator-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend-migrator:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    networks:
      - swarm

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8011:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
