services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile
    container_name: personal-homepage-backend
    restart: always
    env_file:
      - ./apps/backend/.env.dev
    ports:
      - 4600:5000
    depends_on:
      - db
      - migrator
    expose:
      - 4600

  migrator:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile.migrator.dev
    container_name: personal-homepage-migrator
    env_file:
      - ./apps/backend/.env.dev
    depends_on:
      - db
    command: ["./migrate-and-seed.sh"]

  db:
    restart: always
    image: postgres:13
    container_name: personal-homepage-db
    env_file:
      - ./apps/backend/.env
    volumes:
      - ph-db-data:/var/lib/postgresql/data
    ports:
      - 5600:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: personal-homepage-pgadmin4
    env_file:
      - ./apps/backend/.env
    ports:
      - "8600:80"
    volumes:
      - ph-pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  ph-db-data:
  ph-pgadmin-data:
