services:
  backend-prod:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: personal-homepage-backend-prod
    restart: always
    env_file:
      - ./apps/backend/.env.prod
    ports:
      - 6600:5000
    expose:
      - 6600

  migrator-prod:
    build:
      context: ./apps/backend
      dockerfile: ./Dockerfile.migrator.prod
    container_name: personal-homepage-migrator-prod
    env_file:
      - ./apps/backend/.env.prod
