services:
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: personal-homepage-backend-prod
    restart: always
    env_file:
      - .env.production.local
    volumes:
      - ph24-backend-data-prod:/app
    ports:
      - 6600:5000
    networks:
      - personal-homepage-2024
    expose:
      - 6600

volumes:
  ph24-backend-data-prod:

networks:
  personal-homepage-2024:
    external: true
    name: personal-homepage-2024
