services:
  backend-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend:latest
    container_name: personal-homepage-backend-prod
    restart: always
    env_file:
      - ./apps/backend/.env.prod
    ports:
      - 6600:5000
    expose:
      - 6600

  migrator-prod:
    image: ghcr.io/mcesarczyk/personal-homepage-backend-migrator:latest
    container_name: personal-homepage-migrator-prod
    env_file:
      - ./apps/backend/.env.prod
