apiVersion: v1
kind: Service
metadata:
  name: app-db
  namespace: ph
spec:
  selector:
    app: app-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-db
  namespace: ph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-db
  template:
    metadata:
      labels:
        app: app-db
    spec:
      containers:
        - name: app-db
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: db_username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-credentials
                  key: db_password
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
          volumeMounts:
            - name: app-db-storage
              mountPath: /ph/app-db
            - name: secret-volume
              mountPath: "/etc/secret"
              readOnly: true
      volumes:
        - name: app-db-storage
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: app-credentials
