apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ph
spec:
  selector:
    app: app
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: ph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: ghcr.io/mcesarczyk/personal-homepage-backend:latest
          name: app
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:postgres@app-db.ph.svc.cluster.local:5432/postgres?schema=public"
            - name: BACKEND_PORT
              value: "5000"
            - name: PUBLIC_URL
              value: "http://localhost:5000"
            - name: FRONTEND_URL
              value: "http://localhost:4200"
            - name: ADMIN_URL
              value: "http://localhost:4300"
