name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    # types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mcesarczyk/personal-homepage
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/personal-homepage

jobs:
  get-changed:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.changed.outputs.packages }}
      empty: ${{ steps.changed.outputs.empty }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect changed workspaces
        id: changed
        uses: AlexShukel/get-changed-workspaces-action@v2.0.0
        with:
          workspaces: |
            apps/*

  prepare-matrix:
    needs: get-changed
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Generate build matrix
        id: set-matrix
        env:
          CHANGED_PACKAGES: ${{ needs.get-changed.outputs.packages }}
        run: |
          # Parse JSON array of changed packages
          packages=$(echo '${{ toJson(needs.get-changed.outputs.packages) }}' | jq -c '.[]')
          matrix_include=()

          for pkg in $packages; do
            pkg_path=$(echo "$pkg" | jq -r '.path')
            pkg_name=$(echo "$pkg" | jq -r '.name')

            # Always include main app build
            matrix_include+=("{\"package_path\":\"$pkg_path\",\"package_name\":\"$pkg_name\",\"dockerfile\":\"Dockerfile\",\"image_tag\":\"ghcr.io/${{ github.repository_owner }}/$pkg_name\"}")

            # Conditionally include migrator
            if [ -f "$pkg_path/Dockerfile.migrator" ]; then
              matrix_include+=("{\"package_path\":\"$pkg_path\",\"package_name\":\"$pkg_name\",\"dockerfile\":\"Dockerfile.migrator\",\"image_tag\":\"ghcr.io/${{ github.repository_owner }}/$pkg_name-migrator\"}")
            fi
          done

          # Format as valid JSON matrix
          matrix_json="{\"include\":[$(IFS=,; echo "${matrix_include[*]}")]}"
          echo "matrix=$matrix_json" >> $GITHUB_OUTPUT

  build_on_merge:
    needs: [get-changed, prepare-matrix]
    if: ${{ !fromJson(needs.get-changed.outputs.empty) }}
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.prepare-matrix.outputs.matrix) }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: "image=moby/buildkit:v0.11.6"

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/${{ matrix.package.name }}
          file: ./apps/${{ matrix.package.name }}/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE }}-${{ matrix.package.name }}:latest
            ${{ env.DOCKERHUB_IMAGE }}-${{ matrix.package.name }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
