name: Build and Push Docker Image
on:
  pull_request:
    types: [closed]
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mcesarczyk/personal-homepage
  DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/personal-homepage

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_apps: ${{ steps.detect.outputs.changed_apps }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed apps
        id: detect
        run: |
          # Get apps with changed files
          changed_apps=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep -o 'apps/[^/]*' | sort | uniq | sed 's#apps/##')

          # Convert to JSON array
          json_array=$(echo "$changed_apps" | jq -R . | jq -s .)
          echo "changed_apps=$json_array" >> $GITHUB_OUTPUT

  build_on_merge:
    needs: detect-changes
    if: ${{ github.event.pull_request.merged == true && needs.detect-changes.outputs.changed_apps != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: ${{ fromJson(needs.detect-changes.outputs.changed_apps) }}
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: "image=moby/buildkit:v0.11.6"

      - name: Build and push Main Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: ./apps/${{ matrix.package.name }}
          file: ./apps/${{ matrix.package.name }}/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE }}-${{ matrix.package.name }}:latest
            ${{ env.DOCKERHUB_IMAGE }}-${{ matrix.package.name }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Generate base artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Check for Dockerfile.migrator
        id: check-migrator
        run: |
          if [ -f "./apps/${{ matrix.package.name }}/Dockerfile.migrator" ]; then
            echo "migrator_exists=true" >> $GITHUB_OUTPUT
          else
            echo "migrator_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Migrator Docker image
        if: ${{ steps.check-migrator.outputs.migrator_exists == 'true' }}
        id: push-migrator
        uses: docker/build-push-action@v4
        with:
          context: ./apps/${{ matrix.package.name }}
          file: ./apps/${{ matrix.package.name }}/Dockerfile.migrator
          push: true
          tags: |
            ${{ env.DOCKERHUB_IMAGE }}-${{ matrix.package.name }}-migrator:latest
            ${{ env.DOCKERHUB_IMAGE }}-${{ matrix.package.name }}-migrator:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}-migrator:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}-migrator:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Generate migrator artifact attestation
        if: ${{ steps.check-migrator.outputs.migrator_exists == 'true' && steps.push-migrator.conclusion == 'success' }}
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-${{ matrix.package.name }}-migrator
          subject-digest: ${{ steps.push-migrator.outputs.digest }}
          push-to-registry: true
